package main

import (
	"fmt"
	"strings"

	"github.com/DeadSoulf/home-ai-core/internal/windowsclient"
)

const (
	uiLanguageEnglish = "en"
	uiLanguageRussian = "ru"
)

var uiText = map[string]map[string]string{
	uiLanguageEnglish: {},
	uiLanguageRussian: {},
}

func init() {
	add := func(language, key, value string) {
		uiText[language][key] = value
	}
	add(uiLanguageEnglish, "window_title", "HOME AI")
	add(uiLanguageEnglish, "language", "Language")
	add(uiLanguageEnglish, "server", "Server")
	add(uiLanguageEnglish, "user", "User")
	add(uiLanguageEnglish, "password", "Password")
	add(uiLanguageEnglish, "password_hint", "blank = stored credential")
	add(uiLanguageEnglish, "connect_save", "Connect & save")
	add(uiLanguageEnglish, "remote_folder", "Remote folder")
	add(uiLanguageEnglish, "local_source", "Local source")
	add(uiLanguageEnglish, "browse", "Browse...")
	add(uiLanguageEnglish, "destination", "Destination")
	add(uiLanguageEnglish, "interval", "Interval")
	add(uiLanguageEnglish, "conflict", "Conflict")
	add(uiLanguageEnglish, "conflict_stop", "Stop")
	add(uiLanguageEnglish, "conflict_skip", "Skip")
	add(uiLanguageEnglish, "conflict_replace", "Trash + replace")
	add(uiLanguageEnglish, "add_profile", "Add folder")
	add(uiLanguageEnglish, "update_profile", "Save changes")
	add(uiLanguageEnglish, "new_clear", "New / clear")
	add(uiLanguageEnglish, "enable", "Enable")
	add(uiLanguageEnglish, "disable", "Disable")
	add(uiLanguageEnglish, "delete", "Delete")
	add(uiLanguageEnglish, "refresh", "Refresh")
	add(uiLanguageEnglish, "sync_profiles", "Synchronized folders")
	add(uiLanguageEnglish, "autostart_checking", "Autostart: checking...")
	add(uiLanguageEnglish, "sync_now", "Sync now")
	add(uiLanguageEnglish, "enable_agent", "Enable agent")
	add(uiLanguageEnglish, "disable_agent", "Disable agent")
	add(uiLanguageEnglish, "status", "Status")
	add(uiLanguageEnglish, "ready", "Ready")
	add(uiLanguageEnglish, "connecting", "Connecting to Home-AI...")
	add(uiLanguageEnglish, "connection_failed", "Connection failed")
	add(uiLanguageEnglish, "account_required", "Server URL and username are required.")
	add(uiLanguageEnglish, "connected_writable", "Connected. %d writable folder(s) available.")
	add(uiLanguageEnglish, "invalid_interval", "Invalid interval. Use values such as 15m, 1h or 24h.")
	add(uiLanguageEnglish, "required_fields", "Server, user, remote folder and local source are required.")
	add(uiLanguageEnglish, "profile_saved", "Sync profile saved.")
	add(uiLanguageEnglish, "profile_on", "ON")
	add(uiLanguageEnglish, "profile_off", "OFF")
	add(uiLanguageEnglish, "never", "never")
	add(uiLanguageEnglish, "failed", "FAILED")
	add(uiLanguageEnglish, "editing_profile", "Editing profile %s")
	add(uiLanguageEnglish, "new_profile", "New profile.")
	add(uiLanguageEnglish, "select_profile", "Select a sync profile first.")
	add(uiLanguageEnglish, "profile_enabled", "Profile enabled.")
	add(uiLanguageEnglish, "profile_disabled", "Profile disabled.")
	add(uiLanguageEnglish, "delete_confirm", "Delete the selected sync profile?")
	add(uiLanguageEnglish, "profile_deleted", "Profile deleted.")
	add(uiLanguageEnglish, "refreshed", "Refreshed.")
	add(uiLanguageEnglish, "sync_requested", "Sync requested through the running Home-AI agent.")
	add(uiLanguageEnglish, "syncing", "Syncing enabled profiles...")
	add(uiLanguageEnglish, "manual_sync_finished", "Manual sync finished. %d profile(s) processed.")
	add(uiLanguageEnglish, "sync_failed", "Sync failed")
	add(uiLanguageEnglish, "enabling_agent", "Enabling Home-AI background agent...")
	add(uiLanguageEnglish, "agent_enabled", "Background agent enabled and started.")
	add(uiLanguageEnglish, "disabling_agent", "Disabling Home-AI background agent...")
	add(uiLanguageEnglish, "agent_disabled", "Background agent autostart disabled.")
	add(uiLanguageEnglish, "agent_error", "Agent error")
	add(uiLanguageEnglish, "autostart_error", "Autostart status error")
	add(uiLanguageEnglish, "autostart_on", "ON")
	add(uiLanguageEnglish, "autostart_off", "OFF")
	add(uiLanguageEnglish, "agent_running", "running")
	add(uiLanguageEnglish, "agent_stopped", "stopped")
	add(uiLanguageEnglish, "autostart_state", "Autostart: %s  |  Agent: %s")
	add(uiLanguageEnglish, "browse_title", "Select local folder to sync")
	add(uiLanguageEnglish, "browse_no_path", "Windows did not return a filesystem path for the selected folder.")
	add(uiLanguageEnglish, "saved_folder", "Saved folder")
	add(uiLanguageEnglish, "profiles_unavailable", "profiles unavailable")
	add(uiLanguageEnglish, "no_enabled_profiles", "no enabled profiles")
	add(uiLanguageEnglish, "not_synced_yet", "not synced yet")
	add(uiLanguageEnglish, "summary_enabled_new", "%d enabled · not synced yet")
	add(uiLanguageEnglish, "summary_last", "%d enabled · last %s %s")
	add(uiLanguageEnglish, "sync_failed_title", "Home-AI sync failed")
	add(uiLanguageEnglish, "open_log_details", "Open the agent log for details.")
	add(uiLanguageEnglish, "sync_complete_title", "Home-AI sync complete")
	add(uiLanguageEnglish, "profiles_processed", "%d profile(s) processed.")
	add(uiLanguageEnglish, "tray_name", "Home-AI Sync Agent")
	add(uiLanguageEnglish, "settings", "Settings")
	add(uiLanguageEnglish, "open_log", "Open log")
	add(uiLanguageEnglish, "open_sync_profiles", "Open sync profiles")
	add(uiLanguageEnglish, "exit", "Exit")
	add(uiLanguageEnglish, "error_prefix", "Error")
	add(uiLanguageEnglish, "brand_name", "HOME AI")
	add(uiLanguageEnglish, "nav_overview", "Overview")
	add(uiLanguageEnglish, "nav_connection", "Connection")
	add(uiLanguageEnglish, "nav_sync", "Synchronization")
	add(uiLanguageEnglish, "nav_backup", "Backups")
	add(uiLanguageEnglish, "nav_settings", "Settings")
	add(uiLanguageEnglish, "connection_hint", "Connect this PC to your HOME AI server. Credentials stay in Windows Credential Manager.")
	add(uiLanguageEnglish, "sync_hint", "Choose local folders and where they should be stored on HOME AI.")
	add(uiLanguageEnglish, "backup_hint", "Control automatic protection and the schedule for each synchronized folder.")
	add(uiLanguageEnglish, "backup_folder", "Folder")
	add(uiLanguageEnglish, "save_schedule", "Save schedule")
	add(uiLanguageEnglish, "backup_agent_title", "Automatic synchronization")
	add(uiLanguageEnglish, "general_hint", "Keep only the client preferences you normally need.")
	add(uiLanguageEnglish, "general_background_title", "Background operation")
	add(uiLanguageEnglish, "general_background_hint", "HOME AI can keep synchronization running in the Windows user session and show its state in the system tray.")
	add(uiLanguageEnglish, "open_home_folder", "Open folder")
	add(uiLanguageEnglish, "open_folder_unavailable", "Add a synchronized folder first.")
	add(uiLanguageEnglish, "overview_connection", "Connection")
	add(uiLanguageEnglish, "overview_sync_state", "Synchronization")
	add(uiLanguageEnglish, "overview_backup_state", "Automatic protection")
	add(uiLanguageEnglish, "overview_next", "Next run")
	add(uiLanguageEnglish, "overview_last", "Last synchronization")
	add(uiLanguageEnglish, "overview_not_configured", "HOME AI is not configured yet")
	add(uiLanguageEnglish, "overview_hint", "Connect to the server and add the first folder.")
	add(uiLanguageEnglish, "overview_attention", "Synchronization needs attention")
	add(uiLanguageEnglish, "overview_failed_count", "%d folder(s) have an error.")
	add(uiLanguageEnglish, "overview_paused", "Synchronization is paused")
	add(uiLanguageEnglish, "overview_no_enabled", "No synchronized folders are enabled.")
	add(uiLanguageEnglish, "overview_ready", "Ready to synchronize")
	add(uiLanguageEnglish, "overview_enabled_count", "%d folder(s) are protected.")
	add(uiLanguageEnglish, "overview_all_synced", "Everything is synchronized")
	add(uiLanguageEnglish, "overview_connected_to", "Connected\r\n%s · %s")
	add(uiLanguageEnglish, "overview_configured_server", "Configured\r\n%s · %s")
	add(uiLanguageEnglish, "overview_sync_count", "%d active of %d folder(s)")
	add(uiLanguageEnglish, "overview_agent_unknown", "Status unavailable")
	add(uiLanguageEnglish, "overview_agent_on", "Background synchronization is enabled")
	add(uiLanguageEnglish, "overview_agent_off", "Background synchronization is disabled")
	add(uiLanguageEnglish, "overview_next_manual", "Manual start")
	add(uiLanguageEnglish, "overview_last_success", "Successful · %s")
	add(uiLanguageEnglish, "overview_not_synced", "Not yet")
	add(uiLanguageEnglish, "overview_files_current", "Your files are current and protected.")
	add(uiLanguageEnglish, "overview_connected_short", "Connected\r\n%s")
	add(uiLanguageEnglish, "overview_configured_short", "Server configured\r\n%s")
	add(uiLanguageEnglish, "overview_folder", "HOME AI folder")
	add(uiLanguageEnglish, "overview_folder_none", "Not selected")
	add(uiLanguageEnglish, "recent_activity", "Recent activity")
	add(uiLanguageEnglish, "recent_activity_empty", "No recent synchronization activity")
	add(uiLanguageEnglish, "recent_activity_ok", "Synchronized")
	add(uiLanguageEnglish, "recent_activity_error", "Needs attention")
	add(uiLanguageEnglish, "recent_activity_row", "%s\r\n%s · %s")
	add(uiLanguageEnglish, "backup_summary", "Backups")
	add(uiLanguageEnglish, "overview_agent_on_count", "Automatic protection enabled\r\n%d folder(s) active")
	add(uiLanguageEnglish, "storage_summary", "Space on HOME AI")
	add(uiLanguageEnglish, "storage_unknown", "Space unavailable")
	add(uiLanguageEnglish, "storage_connect_hint", "Connect to HOME AI to refresh usage.")
	add(uiLanguageEnglish, "storage_server_hint", "HOME AI did not report folder usage.")
	add(uiLanguageEnglish, "storage_used_of", "%s of %s")
	add(uiLanguageEnglish, "storage_available", "%s available")
	add(uiLanguageEnglish, "storage_unlimited", "No folder quota")
	add(uiLanguageRussian, "window_title", "HOME AI")
	add(uiLanguageRussian, "language", "Язык")
	add(uiLanguageRussian, "server", "Сервер")
	add(uiLanguageRussian, "user", "Пользователь")
	add(uiLanguageRussian, "password", "Пароль")
	add(uiLanguageRussian, "password_hint", "пусто = сохранённый пароль")
	add(uiLanguageRussian, "connect_save", "Подключить и сохранить")
	add(uiLanguageRussian, "remote_folder", "Папка на сервере")
	add(uiLanguageRussian, "local_source", "Локальная папка")
	add(uiLanguageRussian, "browse", "Выбрать...")
	add(uiLanguageRussian, "destination", "Путь назначения")
	add(uiLanguageRussian, "interval", "Интервал")
	add(uiLanguageRussian, "conflict", "Конфликт")
	add(uiLanguageRussian, "conflict_stop", "Остановить")
	add(uiLanguageRussian, "conflict_skip", "Пропустить")
	add(uiLanguageRussian, "conflict_replace", "В корзину + заменить")
	add(uiLanguageRussian, "add_profile", "Добавить папку")
	add(uiLanguageRussian, "update_profile", "Сохранить")
	add(uiLanguageRussian, "new_clear", "Новый / очистить")
	add(uiLanguageRussian, "enable", "Включить")
	add(uiLanguageRussian, "disable", "Выключить")
	add(uiLanguageRussian, "delete", "Удалить")
	add(uiLanguageRussian, "refresh", "Обновить")
	add(uiLanguageRussian, "sync_profiles", "Синхронизируемые папки")
	add(uiLanguageRussian, "autostart_checking", "Автозапуск: проверка...")
	add(uiLanguageRussian, "sync_now", "Синхронизировать сейчас")
	add(uiLanguageRussian, "enable_agent", "Включить агент")
	add(uiLanguageRussian, "disable_agent", "Выключить агент")
	add(uiLanguageRussian, "status", "Состояние")
	add(uiLanguageRussian, "ready", "Готово")
	add(uiLanguageRussian, "connecting", "Подключение к Home-AI...")
	add(uiLanguageRussian, "connection_failed", "Ошибка подключения")
	add(uiLanguageRussian, "account_required", "Укажите адрес сервера и имя пользователя.")
	add(uiLanguageRussian, "connected_writable", "Подключено. Доступно папок для записи: %d.")
	add(uiLanguageRussian, "invalid_interval", "Некорректный интервал. Используйте, например, 15m, 1h или 24h.")
	add(uiLanguageRussian, "required_fields", "Нужно указать сервер, пользователя, папку на сервере и локальную папку.")
	add(uiLanguageRussian, "profile_saved", "Профиль синхронизации сохранён.")
	add(uiLanguageRussian, "profile_on", "ВКЛ")
	add(uiLanguageRussian, "profile_off", "ВЫКЛ")
	add(uiLanguageRussian, "never", "ещё не запускался")
	add(uiLanguageRussian, "failed", "ОШИБКА")
	add(uiLanguageRussian, "editing_profile", "Редактируется профиль %s")
	add(uiLanguageRussian, "new_profile", "Новый профиль.")
	add(uiLanguageRussian, "select_profile", "Сначала выберите профиль синхронизации.")
	add(uiLanguageRussian, "profile_enabled", "Профиль включён.")
	add(uiLanguageRussian, "profile_disabled", "Профиль выключен.")
	add(uiLanguageRussian, "delete_confirm", "Удалить выбранный профиль синхронизации?")
	add(uiLanguageRussian, "profile_deleted", "Профиль удалён.")
	add(uiLanguageRussian, "refreshed", "Обновлено.")
	add(uiLanguageRussian, "sync_requested", "Синхронизация передана запущенному агенту Home-AI.")
	add(uiLanguageRussian, "syncing", "Синхронизация включённых профилей...")
	add(uiLanguageRussian, "manual_sync_finished", "Ручная синхронизация завершена. Обработано профилей: %d.")
	add(uiLanguageRussian, "sync_failed", "Ошибка синхронизации")
	add(uiLanguageRussian, "enabling_agent", "Включение фонового агента Home-AI...")
	add(uiLanguageRussian, "agent_enabled", "Фоновый агент включён и запущен.")
	add(uiLanguageRussian, "disabling_agent", "Выключение фонового агента Home-AI...")
	add(uiLanguageRussian, "agent_disabled", "Автозапуск фонового агента выключен.")
	add(uiLanguageRussian, "agent_error", "Ошибка агента")
	add(uiLanguageRussian, "autostart_error", "Ошибка проверки автозапуска")
	add(uiLanguageRussian, "autostart_on", "ВКЛ")
	add(uiLanguageRussian, "autostart_off", "ВЫКЛ")
	add(uiLanguageRussian, "agent_running", "запущен")
	add(uiLanguageRussian, "agent_stopped", "остановлен")
	add(uiLanguageRussian, "autostart_state", "Автозапуск: %s  |  Агент: %s")
	add(uiLanguageRussian, "browse_title", "Выберите локальную папку для синхронизации")
	add(uiLanguageRussian, "browse_no_path", "Windows не вернула путь файловой системы для выбранной папки.")
	add(uiLanguageRussian, "saved_folder", "Сохранённая папка")
	add(uiLanguageRussian, "profiles_unavailable", "профили недоступны")
	add(uiLanguageRussian, "no_enabled_profiles", "нет включённых профилей")
	add(uiLanguageRussian, "not_synced_yet", "синхронизация ещё не запускалась")
	add(uiLanguageRussian, "summary_enabled_new", "%d включено · синхронизации ещё не было")
	add(uiLanguageRussian, "summary_last", "%d включено · последний результат %s %s")
	add(uiLanguageRussian, "sync_failed_title", "Ошибка синхронизации Home-AI")
	add(uiLanguageRussian, "open_log_details", "Откройте журнал агента для подробностей.")
	add(uiLanguageRussian, "sync_complete_title", "Синхронизация Home-AI завершена")
	add(uiLanguageRussian, "profiles_processed", "Обработано профилей: %d.")
	add(uiLanguageRussian, "tray_name", "Home-AI — Агент синхронизации")
	add(uiLanguageRussian, "settings", "Настройки")
	add(uiLanguageRussian, "open_log", "Открыть журнал")
	add(uiLanguageRussian, "open_sync_profiles", "Открыть профили синхронизации")
	add(uiLanguageRussian, "exit", "Выход")
	add(uiLanguageRussian, "error_prefix", "Ошибка")
	add(uiLanguageRussian, "brand_name", "HOME AI")
	add(uiLanguageRussian, "nav_overview", "Обзор")
	add(uiLanguageRussian, "nav_connection", "Подключение")
	add(uiLanguageRussian, "nav_sync", "Синхронизация")
	add(uiLanguageRussian, "nav_backup", "Резервные копии")
	add(uiLanguageRussian, "nav_settings", "Настройки")
	add(uiLanguageRussian, "connection_hint", "Подключите этот компьютер к серверу HOME AI. Пароль хранится в диспетчере учётных данных Windows.")
	add(uiLanguageRussian, "sync_hint", "Выберите локальные папки и место, куда они будут сохраняться на HOME AI.")
	add(uiLanguageRussian, "backup_hint", "Настройте автоматическую защиту и периодичность для каждой синхронизируемой папки.")
	add(uiLanguageRussian, "backup_folder", "Папка")
	add(uiLanguageRussian, "save_schedule", "Сохранить расписание")
	add(uiLanguageRussian, "backup_agent_title", "Автоматическая синхронизация")
	add(uiLanguageRussian, "general_hint", "Здесь остаются только основные настройки клиента.")
	add(uiLanguageRussian, "general_background_title", "Работа в фоне")
	add(uiLanguageRussian, "general_background_hint", "HOME AI может синхронизировать папки в сеансе Windows и показывать состояние через значок в системном трее.")
	add(uiLanguageRussian, "open_home_folder", "Открыть папку")
	add(uiLanguageRussian, "open_folder_unavailable", "Сначала добавьте папку для синхронизации.")
	add(uiLanguageRussian, "overview_connection", "Подключение")
	add(uiLanguageRussian, "overview_sync_state", "Синхронизация")
	add(uiLanguageRussian, "overview_backup_state", "Автоматическая защита")
	add(uiLanguageRussian, "overview_next", "Следующий запуск")
	add(uiLanguageRussian, "overview_last", "Последняя синхронизация")
	add(uiLanguageRussian, "overview_not_configured", "HOME AI ещё не настроен")
	add(uiLanguageRussian, "overview_hint", "Подключитесь к серверу и добавьте первую папку.")
	add(uiLanguageRussian, "overview_attention", "Синхронизация требует внимания")
	add(uiLanguageRussian, "overview_failed_count", "Ошибок в папках: %d.")
	add(uiLanguageRussian, "overview_paused", "Синхронизация приостановлена")
	add(uiLanguageRussian, "overview_no_enabled", "Нет включённых папок синхронизации.")
	add(uiLanguageRussian, "overview_ready", "Готово к синхронизации")
	add(uiLanguageRussian, "overview_enabled_count", "Защищено папок: %d.")
	add(uiLanguageRussian, "overview_all_synced", "Всё синхронизировано")
	add(uiLanguageRussian, "overview_connected_to", "Подключено\r\n%s · %s")
	add(uiLanguageRussian, "overview_configured_server", "Сервер настроен\r\n%s · %s")
	add(uiLanguageRussian, "overview_sync_count", "Активно %d из %d папок")
	add(uiLanguageRussian, "overview_agent_unknown", "Состояние недоступно")
	add(uiLanguageRussian, "overview_agent_on", "Фоновая синхронизация включена")
	add(uiLanguageRussian, "overview_agent_off", "Фоновая синхронизация выключена")
	add(uiLanguageRussian, "overview_next_manual", "Только вручную")
	add(uiLanguageRussian, "overview_last_success", "Успешно · %s")
	add(uiLanguageRussian, "overview_not_synced", "Ещё не было")
	add(uiLanguageRussian, "overview_files_current", "Ваши файлы актуальны и защищены.")
	add(uiLanguageRussian, "overview_connected_short", "Подключено\r\n%s")
	add(uiLanguageRussian, "overview_configured_short", "Сервер настроен\r\n%s")
	add(uiLanguageRussian, "overview_folder", "Папка HOME AI")
	add(uiLanguageRussian, "overview_folder_none", "Не выбрана")
	add(uiLanguageRussian, "recent_activity", "Последние действия")
	add(uiLanguageRussian, "recent_activity_empty", "Последних операций пока нет")
	add(uiLanguageRussian, "recent_activity_ok", "Синхронизировано")
	add(uiLanguageRussian, "recent_activity_error", "Требует внимания")
	add(uiLanguageRussian, "recent_activity_row", "%s\r\n%s · %s")
	add(uiLanguageRussian, "backup_summary", "Резервные копии")
	add(uiLanguageRussian, "overview_agent_on_count", "Автоматическая защита включена\r\nАктивно папок: %d")
	add(uiLanguageRussian, "storage_summary", "Место на HOME AI")
	add(uiLanguageRussian, "storage_unknown", "Объём недоступен")
	add(uiLanguageRussian, "storage_connect_hint", "Подключение к HOME AI не подтверждено.")
	add(uiLanguageRussian, "storage_server_hint", "HOME AI не сообщил данные об объёме папок.")
	add(uiLanguageRussian, "storage_used_of", "%s из %s")
	add(uiLanguageRussian, "storage_available", "Доступно %s")
	add(uiLanguageRussian, "storage_unlimited", "Без ограничения")
}

func normalizeUILanguage(language string) string {
	switch strings.ToLower(strings.TrimSpace(language)) {
	case "ru", "ru-ru":
		return uiLanguageRussian
	case "en", "en-us", "en-gb":
		return uiLanguageEnglish
	default:
		return uiLanguageEnglish
	}
}

func textForLanguage(language, key string) string {
	language = normalizeUILanguage(language)
	if value := uiText[language][key]; value != "" {
		return value
	}
	return uiText[uiLanguageEnglish][key]
}

func textForLanguagef(language, key string, args ...any) string {
	return fmt.Sprintf(textForLanguage(language, key), args...)
}

func preferredUILanguage() string {
	path, err := defaultClientSettingsPath()
	if err != nil {
		return defaultUILanguage()
	}
	return preferredUILanguageForSettingsPath(path)
}

func preferredUILanguageForSettingsPath(path string) string {
	settings, err := windowsclient.LoadClientSettings(path)
	if err != nil || settings.Language == "" {
		return defaultUILanguage()
	}
	return normalizeUILanguage(settings.Language)
}
